language: node_js
node_js:
  - node
script:
  - npm run test
  - npm run build
deploy:
  provider: npm
  email: 'contact@aresrpg.fr'
  api_key: 'ubrxBLmn8sAaGfEmK8Y89dFLyWGokLYTT5pTQVr+kG+xFm9yUa9GHJuolHQ/OLJIcOyqtyVzRUQjE1AlTYjnrSpw5xOaRxtZ5RJ/XIbo6Y8dl5/cS0fOuihtsQq9ERCyJvJxxrsqqtTrNpKoGk2cs3fjz+Ejinx5hZyANjmf3u14qvOaNbETi0zh/vI2XQo7tWS7hNpVCBNz8iXb3nU06ICcADjt+mFmPa2xOiRw2QGr1VnA1PPi3vFks86W4DlI7Vty9tZqNTPK/ESkURKxMZYyRj0lZQPO3ET7K8l8bVuNMeC6RwudMmx3J3jvNzwth/MnjB4leCRIB0nVyLr4O0gfGD2Egvjadsq5a0VE4fELLk7KIQ+sXibF66THh1Mq0ug9W0KcI+906ewH8bO+QgJwqtdlapL40Nt4osBDS0P37ddCcG7XCF5p9caslJkE9WKo3CysPvj0eE3JWQj36bEksKFwRBOOd/A3pmBd9tizUEjIFVYtTT1NETl8wLAMnUTa9XXiA0ONI9U0LDPDzxgxS7L7UYCa8Y9F4AsT/NAX7DBKnpTqvRMlab2LBUyQixQ3Ck4w0Es9Gb9hS1lDTJivnXfNqQaSHR6VuQPdc94jC0ZstrbgmtdtM6vicJVxtp5ZLy5RP9/pObDbAzq5PTTw+J8v42t8bvbr/WDWGEE='
  # api_key: "$NPM_TOKEN"
  skip_cleanup: true
  script: echo "Deploying to npm ..."
  on:
    tags: true
    branch: master
