name: CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Publish to Registry
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: org/image
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: ghcr.io
      #     tag_semver: true
